from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, Dialog):
        self.AdminWindow = Dialog
        self.AdminWindow.setObjectName("AdminWindow")
        self.AdminWindow.resize(600, 417)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdminWindow.sizePolicy().hasHeightForWidth())
        self.AdminWindow.setSizePolicy(sizePolicy)
        self.adminTabWidget = QtWidgets.QTabWidget(parent=self.AdminWindow)
        self.adminTabWidget.setGeometry(QtCore.QRect(20, 60, 561, 341))
        self.adminTabWidget.setObjectName("adminTabWidget")
        self.usersTab = QtWidgets.QWidget()
        self.usersTab.setObjectName("usersTab")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.usersTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addUserButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.addUserButton.setObjectName("addUserButton")
        self.gridLayout.addWidget(self.addUserButton, 2, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(parent=self.gridLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.deleteUserButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.gridLayout.addWidget(self.deleteUserButton, 3, 0, 1, 1)
        self.adminTabWidget.addTab(self.usersTab, "")
        self.studentsTab = QtWidgets.QWidget()
        self.studentsTab.setObjectName("studentsTab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.studentsTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addStudentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.addStudentButton.setObjectName("addStudentButton")
        self.gridLayout_2.addWidget(self.addStudentButton, 1, 0, 1, 1)
        self.tableView_3 = QtWidgets.QTableView(parent=self.gridLayoutWidget_2)
        self.tableView_3.setObjectName("tableView_3")
        self.gridLayout_2.addWidget(self.tableView_3, 0, 0, 1, 1)
        self.deleteStudentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.deleteStudentButton.setObjectName("deleteStudentButton")
        self.gridLayout_2.addWidget(self.deleteStudentButton, 2, 0, 1, 1)
        self.adminTabWidget.addTab(self.studentsTab, "")
        self.teachersTab = QtWidgets.QWidget()
        self.teachersTab.setObjectName("teachersTab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.teachersTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.deleteTeacherButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.deleteTeacherButton.setObjectName("deleteTeacherButton")
        self.gridLayout_3.addWidget(self.deleteTeacherButton, 2, 0, 1, 1)
        self.tableView_2 = QtWidgets.QTableView(parent=self.gridLayoutWidget_3)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_3.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.addTeacherButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_3)
        self.addTeacherButton.setObjectName("addTeacherButton")
        self.gridLayout_3.addWidget(self.addTeacherButton, 1, 0, 1, 1)
        self.adminTabWidget.addTab(self.teachersTab, "")
        self.subjectsTab = QtWidgets.QWidget()
        self.subjectsTab.setObjectName("subjectsTab")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.subjectsTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.deleteSubjectButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_4)
        self.deleteSubjectButton_2.setObjectName("deleteSubjectButton_2")
        self.gridLayout_4.addWidget(self.deleteSubjectButton_2, 2, 0, 1, 1)
        self.tableView_4 = QtWidgets.QTableView(parent=self.gridLayoutWidget_4)
        self.tableView_4.setObjectName("tableView_4")
        self.gridLayout_4.addWidget(self.tableView_4, 0, 0, 1, 1)
        self.addSubjectButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_4)
        self.addSubjectButton.setObjectName("addSubjectButton")
        self.gridLayout_4.addWidget(self.addSubjectButton, 1, 0, 1, 1)
        self.adminTabWidget.addTab(self.subjectsTab, "")
        self.classesTab = QtWidgets.QWidget()
        self.classesTab.setObjectName("classesTab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(parent=self.classesTab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.deleteClassButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_5)
        self.deleteClassButton.setObjectName("deleteClassButton")
        self.gridLayout_5.addWidget(self.deleteClassButton, 2, 0, 1, 1)
        self.tableView_5 = QtWidgets.QTableView(parent=self.gridLayoutWidget_5)
        self.tableView_5.setObjectName("tableView_5")
        self.gridLayout_5.addWidget(self.tableView_5, 0, 0, 1, 1)
        self.addClassButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_5)
        self.addClassButton.setObjectName("addClassButton")
        self.gridLayout_5.addWidget(self.addClassButton, 1, 0, 1, 1)
        self.adminTabWidget.addTab(self.classesTab, "")
        self.parentsTab = QtWidgets.QWidget()
        self.parentsTab.setObjectName("parentsTab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(parent=self.parentsTab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 511, 291))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.deleteParentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_6)
        self.deleteParentButton.setObjectName("deleteParentButton")
        self.gridLayout_6.addWidget(self.deleteParentButton, 2, 0, 1, 1)
        self.tableView_6 = QtWidgets.QTableView(parent=self.gridLayoutWidget_6)
        self.tableView_6.setObjectName("tableView_6")
        self.gridLayout_6.addWidget(self.tableView_6, 0, 0, 1, 1)
        self.addParentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget_6)
        self.addParentButton.setObjectName("addParentButton")
        self.gridLayout_6.addWidget(self.addParentButton, 1, 0, 1, 1)
        self.adminTabWidget.addTab(self.parentsTab, "")
        self.adminLabel = QtWidgets.QLabel(parent=self.AdminWindow)
        self.adminLabel.setGeometry(QtCore.QRect(30, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adminLabel.setFont(font)
        self.adminLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.adminLabel.setLineWidth(1)
        self.adminLabel.setObjectName("adminLabel")

        self.exitButton = QtWidgets.QPushButton(parent=self.AdminWindow)
        self.exitButton.setGeometry(QtCore.QRect(420, 10, 161, 21))
        self.exitButton.setObjectName("exitButton")
        self.exitButton.clicked.connect(self.openAuthWindow)

        self.retranslateUi(self.AdminWindow)
        self.adminTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self.AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Администратор"))
        self.addUserButton.setText(_translate("AdminWindow", "Добавить пользователя"))
        self.deleteUserButton.setText(_translate("AdminWindow", "Удалить пользователя"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.usersTab), _translate("AdminWindow", "Пользователи"))
        self.addStudentButton.setText(_translate("AdminWindow", "Добавить ученика"))
        self.deleteStudentButton.setText(_translate("AdminWindow", "Удалить ученика"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.studentsTab), _translate("AdminWindow", "Ученики"))
        self.deleteTeacherButton.setText(_translate("AdminWindow", "Удалить учителя"))
        self.addTeacherButton.setText(_translate("AdminWindow", "Добавить учителя"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.teachersTab), _translate("AdminWindow", "Учителя"))
        self.deleteSubjectButton_2.setText(_translate("AdminWindow", "Удалить предмет"))
        self.addSubjectButton.setText(_translate("AdminWindow", "Добавить предмет"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.subjectsTab), _translate("AdminWindow", "Предметы"))
        self.deleteClassButton.setText(_translate("AdminWindow", "Удалить класс"))
        self.addClassButton.setText(_translate("AdminWindow", "Добавить класс"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.classesTab), _translate("AdminWindow", "Классы"))
        self.deleteParentButton.setText(_translate("AdminWindow", "Удалить родителя"))
        self.addParentButton.setText(_translate("AdminWindow", "Добавить родителя"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.parentsTab), _translate("AdminWindow", "Родители"))
        self.adminLabel.setText(_translate("AdminWindow", "admin"))
        self.exitButton.setText(_translate("AdminWindow", "Выйти из ученой записи"))

    def openAuthWindow(self):
        global authWindowDialog
        global authWindowUi

        authWindowDialog = QtWidgets.QDialog()
        authWindowUi = AuthorizationWindow()
        authWindowUi.setupUi(authWindowDialog)



        authWindowDialog.show()



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#
#     adminWindowDialog = QtWidgets.QDialog()
#     adminWindowUi = AdminWindow()
#     adminWindowUi.setupUi(adminWindowDialog)
#
#     adminWindowDialog.show()
#
#     sys.exit(app.exec())
