from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(777, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(28, 70, 721, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.tableView = QtWidgets.QTableView(parent=self.frame_2)
        self.tableView.setGeometry(QtCore.QRect(5, 20, 350, 120))
        self.tableView.setObjectName("tableView")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_12.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_6.setLineWidth(1)
        self.label_6.setMidLineWidth(0)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.tableView_3 = QtWidgets.QTableView(parent=self.frame_3)
        self.tableView_3.setGeometry(QtCore.QRect(5, 20, 350, 120))
        self.tableView_3.setObjectName("tableView_3")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.tableView_4 = QtWidgets.QTableView(parent=self.frame)
        self.tableView_4.setGeometry(QtCore.QRect(0, 20, 350, 120))
        self.tableView_4.setObjectName("tableView_4")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_13.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(0)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.tableView_2 = QtWidgets.QTableView(parent=self.frame_4)
        self.tableView_2.setGeometry(QtCore.QRect(5, 20, 350, 120))
        self.tableView_2.setObjectName("tableView_2")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_10.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_8.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_8.setLineWidth(1)
        self.label_8.setMidLineWidth(0)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.tableView_5 = QtWidgets.QTableView(parent=self.frame_5)
        self.tableView_5.setGeometry(QtCore.QRect(0, 20, 350, 120))
        self.tableView_5.setObjectName("tableView_5")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_14.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(40, 0, 141, 16))
        self.label_7.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_7.setLineWidth(1)
        self.label_7.setMidLineWidth(0)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.tableView_6 = QtWidgets.QTableView(parent=self.frame_6)
        self.tableView_6.setGeometry(QtCore.QRect(0, 20, 350, 120))
        self.tableView_6.setObjectName("tableView_6")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(10, 0, 21, 16))
        self.label_16.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.frame_6, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 361, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(610, 32, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.dateEdit = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(320, 550, 140, 30))
        self.dateEdit.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.dateEdit.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.dateEdit.setAcceptDrops(False)
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 550, 120, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 550, 120, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(30, 56, 361, 20))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Дневник"))
        self.label_4.setText(_translate("Dialog", "Дата"))
        self.label_12.setText(_translate("Dialog", "Пн"))
        self.label_6.setText(_translate("Dialog", "Дата"))
        self.label_11.setText(_translate("Dialog", "Ср"))
        self.label_9.setText(_translate("Dialog", "Дата"))
        self.label_13.setText(_translate("Dialog", "Чт"))
        self.label_5.setText(_translate("Dialog", "Дата"))
        self.label_10.setText(_translate("Dialog", "Вт"))
        self.label_8.setText(_translate("Dialog", "Дата"))
        self.label_14.setText(_translate("Dialog", "Пт"))
        self.label_7.setText(_translate("Dialog", "Дата"))
        self.label_16.setText(_translate("Dialog", "Сб"))
        self.label.setText(_translate("Dialog", "Фамилия"))
        self.label_2.setText(_translate("Dialog", "Отчество"))
        self.label_3.setText(_translate("Dialog", "Имя"))
        self.pushButton.setText(_translate("Dialog", "Выйти из дневника"))
        self.pushButton_2.setText(_translate("Dialog", "Следующая неделя"))
        self.pushButton_3.setText(_translate("Dialog", "Предыдущая неделя"))

